sbt "runMain vexiiriscv.tester.TestBench \
    --with-rvc \
    --with-mul \
    --with-div \
    --with-late-alu \
    --regfile-async \
    --allow-bypass-from 0 \
    --div-radix 4 \
    --performance-counters 4 \
    --load-elf ../../sw_riscv/build/mico.elf \
    --no-rvls-check \
    --print-stats"